"""empty message

Revision ID: d2e4848462e5
Revises: 4a47a01ca8a7
Create Date: 2021-10-12 00:25:40.121880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2e4848462e5'
down_revision = '4a47a01ca8a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'subcategory')
    op.drop_constraint('keyreslink_ibfk_1', 'keyreslink', type_='foreignkey')
    op.drop_column('keyreslink', 'category_id')
    op.add_column('keywords', sa.Column('subcategory', sa.String(length=100), nullable=True))
    op.drop_constraint('keywords_ibfk_1', 'keywords', type_='foreignkey')
    op.drop_column('keywords', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keywords', sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('keywords_ibfk_1', 'keywords', 'categories', ['category_id'], ['id'])
    op.drop_column('keywords', 'subcategory')
    op.add_column('keyreslink', sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('keyreslink_ibfk_1', 'keyreslink', 'categories', ['category_id'], ['id'])
    op.add_column('categories', sa.Column('subcategory', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=True))
    # ### end Alembic commands ###
