"""empty message

Revision ID: 5c13ed6d35c7
Revises: c6b025fe409b
Create Date: 2021-10-01 20:49:01.681369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c13ed6d35c7'
down_revision = 'c6b025fe409b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('total_rating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kakao', sa.Float(), nullable=True),
    sa.Column('naver', sa.Float(), nullable=True),
    sa.Column('sikshin', sa.Float(), nullable=True),
    sa.Column('mango', sa.Float(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('restaurants', sa.Column('integrated_rating', sa.Float(), nullable=True))
    op.drop_column('restaurants', 'total_rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('total_rating', mysql.FLOAT(), nullable=True))
    op.drop_column('restaurants', 'integrated_rating')
    op.drop_table('total_rating')
    # ### end Alembic commands ###
