"""empty message

Revision ID: c6b025fe409b
Revises: dc4ac3379260
Create Date: 2021-10-01 13:43:41.980220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b025fe409b'
down_revision = 'dc4ac3379260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('category', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'category')
    # ### end Alembic commands ###
