"""empty message

Revision ID: dc4ac3379260
Revises: 124a1250db79
Create Date: 2021-10-01 11:01:01.761049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc4ac3379260'
down_revision = '124a1250db79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('img_path', sa.String(length=200), nullable=True))
    op.add_column('reviews', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'name')
    op.drop_column('menus', 'img_path')
    # ### end Alembic commands ###
